/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ufes.pss.gestaodefuncionarios.view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author handaniels
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public PrincipalView() {
        initComponents();
        this.setExtendedState(this.getExtendedState());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVersao = new javax.swing.JLabel();
        lblNumVersao = new javax.swing.JLabel();
        lblNumFuncionarios = new javax.swing.JLabel();
        lblFuncionarios = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFuncionario = new javax.swing.JMenu();
        btnAddFuncionario = new javax.swing.JMenuItem();
        btnBuscarFuncionario = new javax.swing.JMenuItem();
        mnuSalario = new javax.swing.JMenu();
        btnCalcularSalario = new javax.swing.JMenuItem();
        mnuFerramentas = new javax.swing.JMenu();
        btnAlterarLogs = new javax.swing.JMenuItem();
        btnInfoSistema = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Funcionários");
        setSize(new java.awt.Dimension(1600, 900));

        lblVersao.setText("Ver:");

        lblNumVersao.setText("0.0");

        lblNumFuncionarios.setText("00");

        lblFuncionarios.setText("Funcionarios:");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        mnuFuncionario.setText("Funcionário");

        btnAddFuncionario.setText("Adicionar Funcionário");
        mnuFuncionario.add(btnAddFuncionario);

        btnBuscarFuncionario.setText("Buscar Funcionário");
        mnuFuncionario.add(btnBuscarFuncionario);

        jMenuBar1.add(mnuFuncionario);

        mnuSalario.setText("Salário");

        btnCalcularSalario.setText("Calcular Salário");
        mnuSalario.add(btnCalcularSalario);

        jMenuBar1.add(mnuSalario);

        mnuFerramentas.setText("Ferramentas");

        btnAlterarLogs.setText("Alterar Mecanismo de Logs");
        mnuFerramentas.add(btnAlterarLogs);

        btnInfoSistema.setText("Informações do Sistema");
        mnuFerramentas.add(btnInfoSistema);

        jMenuBar1.add(mnuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 866, Short.MAX_VALUE)
                .addComponent(lblFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumFuncionarios)
                .addContainerGap())
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFuncionarios)
                    .addComponent(lblFuncionarios)
                    .addComponent(lblVersao)
                    .addComponent(lblNumVersao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getBtnInfoSistema() {
        return btnInfoSistema;
    }

    public JLabel getLblFuncionarios() {
        return lblFuncionarios;
    }

    public void setLblFuncionarios(JLabel lblFuncionarios) {
        this.lblFuncionarios = lblFuncionarios;
    }

    public JLabel getLblNumFuncionarios() {
        return lblNumFuncionarios;
    }

    public void setLblNumFuncionarios(JLabel lblNumFuncionarios) {
        this.lblNumFuncionarios = lblNumFuncionarios;
    }

    public JLabel getLblNumVersao() {
        return lblNumVersao;
    }

    public void setLblNumVersao(JLabel lblNumVersao) {
        this.lblNumVersao = lblNumVersao;
    }

    public JLabel getLblVersao() {
        return lblVersao;
    }

    public void setLblVersao(JLabel lblVersao) {
        this.lblVersao = lblVersao;
    }

    public void setBtnInfoSistema(JMenuItem btnInfoSistema) {
        this.btnInfoSistema = btnInfoSistema;
    }

    public JMenuItem getBtnAddFuncionario() {
        return btnAddFuncionario;
    }

    public void setBtnAddFuncionario(JMenuItem btnAddFuncionario) {
        this.btnAddFuncionario = btnAddFuncionario;
    }

    public JMenuItem getBtnAlterarLogs() {
        return btnAlterarLogs;
    }

    public void setBtnAlterarLogs(JMenuItem btnAlterarLogs) {
        this.btnAlterarLogs = btnAlterarLogs;
    }

    public JMenuItem getBtnBuscarFuncionario() {
        return btnBuscarFuncionario;
    }

    public void setBtnBuscarFuncionario(JMenuItem btnBuscarFuncionario) {
        this.btnBuscarFuncionario = btnBuscarFuncionario;
    }

    public JMenuItem getBtnCalcularSalario() {
        return btnCalcularSalario;
    }

    public void setBtnCalcularSalario(JMenuItem btnCalcularSalario) {
        this.btnCalcularSalario = btnCalcularSalario;
    }

    public JDesktopPane getDesktop() {
        return desktop;
    }

    public void setDesktop(JDesktopPane desktop) {
        this.desktop = desktop;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getMnuFerramentas() {
        return mnuFerramentas;
    }

    public void setMnuFerramentas(JMenu mnuFerramentas) {
        this.mnuFerramentas = mnuFerramentas;
    }

    public JMenu getMnuFuncionario() {
        return mnuFuncionario;
    }

    public void setMnuFuncionario(JMenu mnuFuncionario) {
        this.mnuFuncionario = mnuFuncionario;
    }

    public JMenu getMnuSalario() {
        return mnuSalario;
    }

    public void setMnuSalario(JMenu mnuSalario) {
        this.mnuSalario = mnuSalario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAddFuncionario;
    private javax.swing.JMenuItem btnAlterarLogs;
    private javax.swing.JMenuItem btnBuscarFuncionario;
    private javax.swing.JMenuItem btnCalcularSalario;
    private javax.swing.JMenuItem btnInfoSistema;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblNumFuncionarios;
    private javax.swing.JLabel lblNumVersao;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JMenu mnuFerramentas;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenu mnuSalario;
    // End of variables declaration//GEN-END:variables
}
