/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pss.gestaodefuncionarios.view;

import javax.swing.JButton;

/**
 *
 * @author handaniels
 */
public class SistemaDeLogsView extends javax.swing.JInternalFrame {

    /**
     * Creates new form SistemaDeLogsVIew
     */
    public SistemaDeLogsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXML = new javax.swing.JButton();
        btnJSON = new javax.swing.JButton();
        btnTXT = new javax.swing.JButton();

        setClosable(true);
        setTitle("Escolha um Sistema de Logs");

        btnXML.setText("XML");

        btnJSON.setText("JSON");

        btnTXT.setText("TXT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnXML)
                .addGap(18, 18, 18)
                .addComponent(btnTXT)
                .addGap(18, 18, 18)
                .addComponent(btnJSON)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXML)
                    .addComponent(btnJSON)
                    .addComponent(btnTXT))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnJSON() {
        return btnJSON;
    }

    public void setBtnJSON(JButton btnJSON) {
        this.btnJSON = btnJSON;
    }

    public JButton getBtnTXT() {
        return btnTXT;
    }

    public void setBtnTXT(JButton btnTXT) {
        this.btnTXT = btnTXT;
    }

    public JButton getBtnXML() {
        return btnXML;
    }

    public void setBtnXML(JButton btnXML) {
        this.btnXML = btnXML;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJSON;
    private javax.swing.JButton btnTXT;
    private javax.swing.JButton btnXML;
    // End of variables declaration//GEN-END:variables
}
